import test from 'node:test';import assert from 'node:assert/strict';
import {BridgeStore} from '../src/store.ts';import {ReceiveService} from '../src/receive-service.mjs';import {CreationWorker} from '../src/creation-worker.mjs';import {TEST_TARGET,allowedTasks} from '../src/targets.mjs';import {bumpSelection} from '../src/tasks.mjs';
const ID='11111111-2222-4333-8444-555555555555';
const event=(text,id='new',user='owner')=>({app_id:'cli_test',sender:{sender_type:'user',tenant_key:'t',sender_id:{open_id:user}},message:{message_id:id,chat_id:'c',chat_type:'p2p',message_type:'text',content:JSON.stringify({text})}});
function setup(t,overrides={}){const store=new BridgeStore(':memory:');t.after(()=>store.close());store.bind('t','c','owner',TEST_TARGET);const service=new ReceiveService(store,{appId:'cli_test',targetThreadId:TEST_TARGET,mode:'desktop-test'});let calls=0;const adapter={prepare:async()=>{},create:async()=>{calls++;return {threadId:ID,hostId:'local'};},readCreated:async()=>({thread:{id:ID,kind:'codex',hostId:'local',title:'新任务',status:{type:'idle'}}}),...overrides};return {store,service,adapter,worker:new CreationWorker(store,adapter),calls:()=>calls};}
test('new command creates once, registers and switches; duplicate input never recreates',async t=>{const f=setup(t);f.service.accept(event('/rc new 新任务'),1000);await f.worker.tick(1001);f.service.accept(event('/rc new 新任务'),1002);await f.worker.tick(1002);assert.equal(f.calls(),1);assert.equal(f.store.db.prepare('SELECT target_id FROM bindings').get().target_id,ID);assert.equal(allowedTasks(f.store).get(ID),'新任务');f.service.accept(event('原文','body'),1003);assert.equal(f.store.db.prepare("SELECT target_id FROM inbox WHERE original_text='原文'").get().target_id,ID);});
test('ordinary text while creation pending is never sent to previous task',t=>{const f=setup(t);f.service.accept(event('/rc new 新任务'),1000);f.service.accept(event('不能发到旧任务','body'),1001);assert.equal(f.store.get(2).delivery,'cancelled');assert.match(f.store.pendingReplies().find(r=>r.inbox_id===2).body,/未投递/);});
test('ambiguous create and restart do not replay side effect',async t=>{let calls=0;const f=setup(t,{create:async()=>{calls++;throw Error('timeout');}});f.service.accept(event('/rc new 新任务'),1000);await f.worker.tick(1001);const restarted=new CreationWorker(f.store,f.adapter);restarted.recover();await restarted.tick(1002);assert.equal(calls,1);assert.equal(f.store.db.prepare('SELECT state FROM creation_requests').get().state,'unknown');assert.equal(f.store.db.prepare('SELECT target_id FROM bindings').get().target_id,TEST_TARGET);});
test('crash at creating boundary becomes unknown without create',async t=>{const f=setup(t);f.service.accept(event('/rc new 新任务'),1000);f.store.db.exec("UPDATE creation_requests SET state='creating'");f.worker.recover();await f.worker.tick(1001);assert.equal(f.calls(),0);assert.equal(f.store.db.prepare('SELECT state FROM creation_requests').get().state,'unknown');});
test('known created ID is verified after restart without recreating and manual selection wins',async t=>{let ready=false;const f=setup(t,{readCreated:async()=>{if(!ready)throw Error('not ready');return {thread:{id:ID,kind:'codex',hostId:'local',title:'新任务'}};}});f.service.accept(event('/rc new 新任务'),1000);await f.worker.tick(1001);bumpSelection(f.store,'t','c');ready=true;const w=new CreationWorker(f.store,f.adapter);w.recover();await w.tick(1002);assert.equal(f.calls(),1);assert.equal(f.store.db.prepare('SELECT target_id FROM bindings').get().target_id,TEST_TARGET);assert.equal(allowedTasks(f.store).get(ID),'新任务');assert.match(f.store.pendingReplies().at(-1).body,/保留最新选择/);});
test('bad title, unauthorized sender and additional pending create cannot create',async t=>{const f=setup(t);f.service.accept(event('/rc new','bad'),1000);assert.equal(f.service.accept(event('/rc new 其他','intruder','other'),1000).accepted,false);f.service.accept(event('/rc new 新任务'),1000);f.service.accept(event('/rc new 第二个','second'),1000);await f.worker.tick(1001);assert.equal(f.calls(),1);});
test('pause remains set and unavailable connection eventually reports no creation',async t=>{const f=setup(t,{prepare:async()=>{throw Error('offline');}});f.store.pause('t','c',true);f.service.accept(event('/rc new 新任务'),1000);await f.worker.tick(1001);await f.worker.tick(301000);assert.equal(f.calls(),0);assert.equal(f.store.db.prepare('SELECT state FROM creation_requests').get().state,'failed');assert.equal(f.store.db.prepare('SELECT paused FROM bindings').get().paused,1);});
