import test from 'node:test';
import assert from 'node:assert/strict';
import {BridgeStore} from '../src/store.ts';
import {StopWorker,requestStop} from '../src/stop-worker.mjs';
function fixture(t,transport){const store=new BridgeStore(':memory:');t.after(()=>store.close());store.bind('tenant','chat','owner','target');const state={thread:{id:'target',status:{type:'active'}},turns:[{id:'turn1',status:'inProgress'}]};const worker=new StopWorker(store,{read:async()=>state},'target',transport);store.receive({messageId:'stop',tenantId:'tenant',chatId:'chat',userId:'owner',text:'/rc stop'});requestStop(store,1,'target',1000);return {store,worker,state};}
test('stop pauses queued work and duplicate request stays idempotent',t=>{const {store}=fixture(t);store.receive({messageId:'next',tenantId:'tenant',chatId:'chat',userId:'owner',text:'task'});requestStop(store,1,'target',2000);assert.equal(store.claim('target',true,[]),null);assert.equal(store.db.prepare('SELECT count(*) n FROM stop_requests').get().n,1);assert.equal(store.get(1).delivery,'cancelled');});
test('only observed interruption of captured turn confirms stop',async t=>{let calls=0;const {store,worker,state}=fixture(t,async args=>{calls++;assert.equal(args.turnId,'turn1');});await worker.tick(1001);assert.equal(store.db.prepare('SELECT state FROM stop_requests').get().state,'dispatched');state.turns.unshift({id:'unrelated',status:'interrupted'});await worker.tick(1002);assert.equal(store.db.prepare('SELECT state FROM stop_requests').get().state,'dispatched');state.turns[1].status='interrupted';await worker.tick(1003);assert.equal(store.db.prepare('SELECT state FROM stop_requests').get().state,'confirmed');assert.equal(calls,1);});
test('uncertain click and process recovery never click again',async t=>{let calls=0;const f=fixture(t,async()=>{calls++;throw Error('timeout');});await f.worker.tick(1001);const restarted=new StopWorker(f.store,{read:async()=>f.state},'target',async()=>calls++);await restarted.tick(1002);await restarted.tick(61000);assert.equal(calls,1);assert.equal(f.store.db.prepare('SELECT state FROM stop_requests').get().state,'unknown');});
test('wrong task identity never invokes stop',async t=>{let calls=0;const f=fixture(t,async()=>calls++);f.state.thread.id='other';await f.worker.tick(1001);assert.equal(calls,0);assert.equal(f.store.db.prepare('SELECT state FROM stop_requests').get().state,'failed');});
test('natural completion is not reported as interrupted',async t=>{const f=fixture(t,async()=>{});await f.worker.tick(1001);f.state.turns[0].status='completed';await f.worker.tick(1002);assert.equal(f.store.db.prepare('SELECT state FROM stop_requests').get().state,'finished');});
test('idle and unavailable transport return honest results',async t=>{const f=fixture(t);await f.worker.tick(1001);assert.equal(f.store.db.prepare('SELECT state FROM stop_requests').get().state,'failed');});
