import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {BridgeStore} from '../src/store.ts';
const msg=(messageId='m1')=>({messageId,tenantId:'tenant',userId:'owner',chatId:'chat',text:'原文\n停止  不应被改写'});
function fixture(t,path=':memory:') {const s=new BridgeStore(path);t.after(()=>s.close());s.bind('tenant','chat','owner','target');return s;}
test('receipt and reply are durable together; duplicate does not enqueue again',t=>{const s=fixture(t);const a=s.receive(msg());assert.deepEqual(s.receive(msg()),{id:a.id,duplicate:true});assert.equal(s.pendingReplies().length,1);assert.equal(s.get(a.id).original_text,msg().text)});
test('reject unknown sender and conflicting duplicate',t=>{const s=fixture(t);assert.throws(()=>s.receive({...msg(),userId:'stranger'}));s.receive(msg());assert.throws(()=>s.receive({...msg(),text:'changed'}))});
test('busy or paused target cannot claim',t=>{const s=fixture(t);s.receive(msg());assert.equal(s.claim('target',false,[]),null);s.pause('tenant','chat',true);assert.equal(s.claim('target',true,[]),null);s.pause('tenant','chat',false);assert.equal(s.claim('target',true,['old']).baseline_json,'["old"]')});
test('restart leaves in-flight send unknown and blocks next send',t=>{const dir=mkdtempSync(join(tmpdir(),'remotecontrol-test-'));t.after(()=>rmSync(dir,{recursive:true,force:true}));const path=join(dir,'bridge.sqlite');let s=new BridgeStore(path);s.bind('tenant','chat','owner','target');const a=s.receive(msg());s.receive(msg('m2'));s.claim('target',true,[]);s.close();s=new BridgeStore(path);try{assert.equal(s.recover(),1);assert.equal(s.get(a.id).delivery,'delivery_unknown');assert.equal(s.claim('target',true,[]),null);assert.equal(s.pendingReplies().length,2)}finally{s.close()}});
test('delivery and execution differ; matching final reply unblocks queue once',t=>{const s=fixture(t);const a=s.receive(msg());s.receive(msg('m2'));s.claim('target',true,[]);s.markDelivery(a.id,'delivered','turn');assert.equal(s.claim('target',true,[]),null);assert.throws(()=>s.recordOutcome(a.id,'wrong','completed','done'));s.recordOutcome(a.id,'turn','interrupted','已停止');s.recordOutcome(a.id,'turn','interrupted','已停止');assert.equal(s.pendingReplies().length,3);assert.equal(s.claim('target',true,['turn']).message_id,'m2')});
test('long final replies preserve Unicode and chunk ordering across duplicate outcome',t=>{const s=fixture(t);const a=s.receive(msg());s.claim('target',true,[]);s.markDelivery(a.id,'delivered','turn');const text='😀中文\n'.repeat(1400);s.recordOutcome(a.id,'turn','completed',text);s.recordOutcome(a.id,'turn','completed',text);const parts=s.pendingReplies().filter(x=>x.dedup_key.startsWith('outcome:'));assert.equal(parts.map(x=>x.body).join(''),text);assert.ok(parts.every(x=>Array.from(x.body).length<=2000))});
